#!/bin/sh

# automount tftp server

mkdir -p /mnt/tftp
automount /mnt/tftp 'ifup -a && mount -t tftp $global.net.server /mnt/tftp'

# automount nfs server's nfsroot

mkdir -p /mnt/nfs
automount /mnt/nfs 'ifup -a && mount -t nfs ${global.net.server}:/srv/nfs/${global.hostname} /mnt/nfs'

# automount ubifs from nand partition named `sys`

automount -d /mnt/nand 'ubiattach /dev/orion_nand0.sys && mount -t ubifs /dev/orion_nand0.sys.ubi.root /mnt/nand'
